### ISSUE TITLE
Getting an error while doing inference

### ISSUE THREAD

**Issue by ofirkris** [ayhokuyan/CartooNet#1]
For
' make infer CODE=scripts/whiteboxirbgan.py CKPT=ckpt/pretrained_irb.ckpt '

It's throwing the following error:

AttributeError: 'NoneType' object has no attribute 'split'
makefile:17: recipe for target 'infer' failed

**Comment by ayhokuyan** [comment]
You need to specify the inference target using 'EXTRA=image_path:[Image Path]'

**Comment by ofirkris** [comment]
Thanks for pointing this out, still getting  errors  though
Running
# make infer CODE=scripts/whiteboxirbgan.py CKPT=ckpt/pretrained_irb.ckpt EXTRA=jordan.jpg

Error:
'
whiteboxirbgan.py: error: unrecognized arguments: --jordan.jpg
makefile:17: recipe for target 'infer' failed
make: *** [infer] Error 2
'

**Comment by ayhokuyan** [comment]
you should exactly write,  'EXTRA=image_path:' then the image path. Sorry for the inconvenience, this is how the adapted repo worked originally.

**Comment by ofirkris** [comment]
Worked, thanks!
